# Generated by Django 4.0.1 on 2022-01-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
                ('imagenmarca', models.ImageField(upload_to='photos/franquicia/marca', verbose_name='Imagen Marca')),
                ('imagenlocal', models.ImageField(upload_to='photos/franquicia/local', verbose_name='Imagen Local')),
                ('imagenlogo', models.ImageField(upload_to='photos/franquicia/logo', verbose_name='Imagen Logo')),
                ('categoria', models.ManyToManyField(related_name='marcas', to='marca.Categoria')),
                ('directorio', models.ManyToManyField(blank=True, related_name='marcas', to='marca.Directorio')),
                ('estado', models.ForeignKey(blank=True, help_text='Recuerde que solo puede agregar 9 marcas en Promoción y solo 6 marcas en Nuevo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='marca.estado')),
                ('ubicacion', models.ManyToManyField(related_name='marcas', to='marca.Ubicacion')),
            ],
        ),
    ]
