# Generated by Django 4.0.1 on 2022-01-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='categoria',
        ),
        migrations.AddField(
            model_name='marca',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='marca.categoria'),
            preserve_default=False,
        ),
    ]
