# Generated by Django 4.0.1 on 2022-02-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0002_remove_marca_categoria_marca_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True, verbose_name='Número de Estrellas')),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Rango de Inversión')),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True, verbose_name='Prioridad en orden de franquicias')),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.estrellas', verbose_name='Número de estrellas'),
        ),
        migrations.AddField(
            model_name='marca',
            name='inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.inversion', verbose_name='Rango de Inversión'),
        ),
        migrations.AddField(
            model_name='marca',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.prioridad', verbose_name='Prioridad en el orden de franquicias'),
        ),
    ]
