# Generated by Django 4.0.1 on 2022-02-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0003_estrellas_inversion_prioridad_marca_estrellas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='estrellas',
        ),
        migrations.DeleteModel(
            name='Estrellas',
        ),
    ]
