# Generated by Django 4.0.1 on 2022-02-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0004_remove_marca_estrellas_delete_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='iconofp',
            field=models.CharField(max_length=10, null=True, verbose_name='Icono de la Categoría'),
        ),
    ]
