# Generated by Django 4.0.1 on 2022-02-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0005_categoria_iconofp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='inversion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marca.inversion', verbose_name='Rango de Inversión'),
            preserve_default=False,
        ),
    ]
