# Generated by Django 4.0.1 on 2022-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0006_alter_marca_inversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='estrellas',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, help_text='Número de estrellas que se le asigna a la marca'),
            preserve_default=False,
        ),
    ]
