# Generated by Django 4.0.1 on 2022-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0007_marca_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='estrellas',
            field=models.IntegerField(choices=[('Una', '1'), ('Dos', '2'), ('Tres', '3'), ('Cuatro', '4'), ('Cinco', '5')], help_text='Número de estrellas que se le asigna a la marca'),
        ),
    ]
