# Generated by Django 4.0.1 on 2022-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0008_alter_marca_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='valor',
            field=models.IntegerField(null=True, unique=True, verbose_name='Prioridad en orden de franquicias'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estrellas',
            field=models.CharField(choices=[('1', 'Una'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], help_text='Número de estrellas que se le asigna a la marca', max_length=5),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre de la Prioridad'),
        ),
    ]
