# Generated by Django 4.0.1 on 2022-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0009_prioridad_valor_alter_marca_estrellas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='altimagenlocal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atributo alt de la Imagen Local'),
        ),
        migrations.AddField(
            model_name='marca',
            name='altimagenlogo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atributo alt de la Imagen Logo'),
        ),
        migrations.AddField(
            model_name='marca',
            name='altimagenmarca',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Atributo alt de la Imagen Marca'),
        ),
        migrations.AddField(
            model_name='marca',
            name='urlmarca',
            field=models.TextField(default=1, help_text='Url de la marca por ejemplo bubble-waffle', max_length=50, verbose_name='Url de la marca'),
            preserve_default=False,
        ),
    ]
