# Generated by Django 4.0.1 on 2022-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0010_marca_altimagenlocal_marca_altimagenlogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='altimagenlocal',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo alt de la Imagen Local'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='altimagenlogo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo alt de la Imagen Logo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='altimagenmarca',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo alt de la Imagen Marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='urlmarca',
            field=models.CharField(help_text='Url de la marca por ejemplo bubble-waffle', max_length=50, verbose_name='Url de la marca'),
        ),
    ]
