# Generated by Django 4.0.1 on 2022-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0011_alter_marca_altimagenlocal_alter_marca_altimagenlogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='titleimagenlocal',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo title de la Imagen Local'),
        ),
        migrations.AddField(
            model_name='marca',
            name='titleimagenlogo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo title de la Imagen Logo'),
        ),
        migrations.AddField(
            model_name='marca',
            name='titleimagenmarca',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Atributo title de la Imagen Marca'),
        ),
    ]
