# Generated by Django 4.0.1 on 2022-10-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0015_alter_detalle_marca_cuerpo_promesa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_marca',
            name='url',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url de la Marca'),
        ),
    ]
