# Generated by Django 4.0.1 on 2022-11-02 20:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0017_remove_detalle_marca_alt_imagen_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_marca',
            name='color_detalle_marca',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
