# Generated by Django 4.0.1 on 2022-11-02 20:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0018_detalle_marca_color_detalle_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_marca',
            name='color_detalle_marca',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
