# Generated by Django 4.0.1 on 2022-11-02 20:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0019_alter_detalle_marca_color_detalle_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_marca',
            name='color_promesa_valor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
