# Generated by Django 4.0.1 on 2022-11-07 19:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0021_detalle_marca_color_ocho_cajas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_marca',
            name='color_boton_formulario',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
