# Generated by Django 4.0.1 on 2022-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0024_detalle_marca_color_texto_cuerpo_promesa_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(help_text='El máximo de caracteres es 150', max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estrellas',
            field=models.CharField(blank=True, choices=[('1', 'Una'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], help_text='Proximamente', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagenlocal',
            field=models.ImageField(help_text='Tamaño de la imagen 480 de ancho x 338 de alto', upload_to='photos/franquicia/local', verbose_name='Imagen Local'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagenmarca',
            field=models.ImageField(help_text='Tamaño de la imagen 480 de ancho x 338 de alto', upload_to='photos/franquicia/marca', verbose_name='Imagen Marca'),
        ),
    ]
