# Generated by Django 4.0.1 on 2022-11-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0025_alter_marca_descripcion_alter_marca_estrellas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='estrellas',
        ),
    ]
