# Generated by Django 4.0.1 on 2022-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0026_remove_marca_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_marca',
            name='valor_renovacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor Renovación'),
        ),
    ]
