# Generated by Django 4.0.1 on 2022-11-17 16:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0027_alter_detalle_marca_valor_renovacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_marca',
            name='color_puntos_carrusel',
            field=colorfield.fields.ColorField(default='#d6d6d6', image_field=None, max_length=18, samples=None),
        ),
    ]
