# Generated by Django 4.0.1 on 2022-11-18 20:48

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0028_detalle_marca_color_puntos_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_marca',
            name='color_puntos_carrusel',
            field=colorfield.fields.ColorField(default='#d6d6d6', help_text='Color para los puntos o circulos que aparecen debajo del carrusel de imagenes en pantallas pequeñas', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_banner',
            field=models.ImageField(help_text='Tamaño de la imagen 1920px de ancho x 856px de alto', upload_to='photos/detalle-franquicias/banner', verbose_name='Imagen Banner'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_detalle_marca',
            field=models.ImageField(help_text='Tamaño de la imagen 96px de alto', upload_to='photos/detalle-franquicias/detalle-marca', verbose_name='Imagen Detalle Marca'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_formulario',
            field=models.ImageField(help_text='Tamaño de la imagen 150px de alto', upload_to='photos/detalle-franquicias/formulario', verbose_name='Imagen Formulario'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_1',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-1', verbose_name='Imagen Local 1'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_2',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-2', verbose_name='Imagen Local 2'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_3',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-3', verbose_name='Imagen Local 3'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_4',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-4', verbose_name='Imagen Local 4'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_5',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-5', verbose_name='Imagen Local 5'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_local_6',
            field=models.ImageField(help_text='Tamaño de la imagen 366px de ancho x 250px de alto', upload_to='photos/detalle-franquicias/local-6', verbose_name='Imagen Local 6'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='imagen_producto',
            field=models.ImageField(help_text='Tamaño de la imagen 224px de alto', upload_to='photos/detalle-franquicias/producto', verbose_name='Imagen Producto'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='nombre',
            field=models.CharField(help_text='Este item sirve para saber de que página llegan los formularios', max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagenlogo',
            field=models.ImageField(help_text='Tamaño de la imagen 40 de ancho x 40 de alto', upload_to='photos/franquicia/logo', verbose_name='Imagen Logo'),
        ),
    ]
