# Generated by Django 4.0.1 on 2022-11-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0029_alter_detalle_marca_color_puntos_carrusel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='detalle_marca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.detalle_marca', verbose_name='Detalle Marcas'),
        ),
    ]
