# Generated by Django 4.0.1 on 2022-11-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0030_marca_detalle_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='urlmarca',
        ),
    ]
