# Generated by Django 4.0.1 on 2022-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0031_remove_marca_urlmarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='urlmarca',
            field=models.CharField(blank=True, help_text='Url de la marca por ejemplo bubble-waffle', max_length=50, null=True, verbose_name='Url de la marca'),
        ),
    ]
