# Generated by Django 4.0.1 on 2022-12-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0034_alter_categoria_iconofp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_marca',
            name='descripcion',
            field=models.TextField(help_text='Máximo 300 caracteres', max_length=300, verbose_name='Descripción'),
        ),
    ]
