# Generated by Django 4.2.7 on 2025-01-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0035_alter_detalle_marca_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_marca',
            name='description_html',
            field=models.CharField(blank=True, help_text='Máximo 160 caracteres', max_length=160, null=True, verbose_name='Description HTML'),
        ),
        migrations.AddField(
            model_name='detalle_marca',
            name='script_clientify',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Script Clientify'),
        ),
        migrations.AddField(
            model_name='detalle_marca',
            name='title_html',
            field=models.CharField(blank=True, help_text='Máximo 70 caracteres', max_length=70, null=True, verbose_name='Title HTML'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='franquicias_en_ecuador',
            field=models.CharField(default=0, max_length=20, verbose_name='Número de Franquicias en Ecuador'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='ganancia_mensual',
            field=models.CharField(max_length=20, verbose_name='Ganancia Mensual'),
        ),
        migrations.AlterField(
            model_name='detalle_marca',
            name='valor_renovacion',
            field=models.IntegerField(default=0, help_text='Ingrese -1 para obtener un (-) o -2 para obtener (N/A)', verbose_name='Valor Renovación'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(help_text='El máximo de caracteres es 160', max_length=160, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Se recomienda agregar 9 marcas en Promoción y 9 marcas en Nuevo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='marca.estado'),
        ),
    ]
